spring:
  application:
    name: rest-with-spring-boot-and-java
  profiles:
    # macOS (PostgreSQL): active: ${SPRING_PROFILES_ACTIVE:postgresql}
    # Windows (MySQL): active: ${SPRING_PROFILES_ACTIVE:mysql}
    active: ${SPRING_PROFILES_ACTIVE:postgresql}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

logging:
  level:
    #root: WARN
    br.com.campos: DEBUG

springdoc:
  paths-to-match:
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true